#!/bin/sh

# Make sure user info is setup for this repository

if [[ -z $(git config user.email) || -z $(git config user.name) ]] >/dev/null 2>&1
then
    echo "Error: user info missing for this repository."
    echo
    echo "Set up user info with:"
    echo "  git config --local user.name <NAME>"
    echo "  git config --local user.email <EMAIL>"

    exit 1
fi
