set guifont=Monaco:h13
set cursorline

" remove scrollbars
set guioptions-=rL
" remove toolbar
set guioptions-=T
" don't use GUI dialogs
set guioptions+=c
" don't use GUI tabs
set guioptions-=e
" turn off cursor blinking
set guicursor+=a:blinkon0

if has("gui_macvim")
  " window zoom
  nnoremap <space>wv :set lines=999<cr>
  nnoremap <space>wz :set lines=999 <bar> set columns=999<cr>

  func! s:UpdateBackground()
    if v:os_appearance == 1
      set background=dark
    else
      set background=light
    endif
    redraw!
  endfunc

  autocmd! OSAppearanceChanged * call s:UpdateBackground()
end

