autocmd ColorSchemePre PaperColor set background=light

if has("gui_macvim")
  " color scheme
  let g:xcodehc_dim_punctuation = 1
  silent! colorscheme xcodehc

  func! s:UpdateBackground()
    if v:os_appearance == 1
      set background=dark
    else
      set background=light
    endif
    redraw!
  endfunc

  autocmd OSAppearanceChanged * call s:UpdateBackground()

  " remove scrollbars
  set guioptions-=r
  set guioptions-=L
  " don't use GUI dialogs
  set guioptions+=c
  " don't use GUI tabs
  set guioptions-=e
  " turn off cursor blinking
  set guicursor+=a:blinkon0

  set columns=100
  set lines=50
  set cursorline
  set guifont=Monaco:h13
end
