# Author : Michele Campeotto <micampe@me.com>

"ui.selection" = { fg = "black", bg = "green" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.primary" = { fg = "black", bg = "red" }
"ui.cursor.match" = { fg = "red" }
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "white", bg = "black" }
"ui.statusline" = { fg = "black", bg = "light-gray", modifiers = [ "bold" ] }
"ui.statusline.inactive" = { fg = "black", bg = "gray", modifiers = [ "bold" ] }
"ui.statusline.insert" = { bg = "light-green" }
"ui.statusline.select" = { bg = "light-blue" }
"ui.menu" = { fg = "white", bg = "blue" }
"ui.menu.selected" = { bg = "white", fg = "black" }
"ui.popup" = { fg = "white", bg = "234" }
# selected line in pickers
"ui.text.focus" = { fg = "blue", modifiers = [] }
# search matches in pickers
"special" = { fg = "blue", modifiers = [ "underlined"] }
"ui.help" = { fg = "white", bg = "light-blue" }
"ui.virtual.jump-label" = { fg = "cyan" }
"ui.window" = { fg = "236", bg = "black" }

"string" = { fg = "yellow" }
"constant" = { fg = "light-cyan" }
"constant.numeric" = { fg = "white" }
"comment" = { fg = "gray" }
"operator" = { fg = "white" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "gray"

"warning" = { fg = "light-yellow" }
"error" = { fg = "light-red" }
"hint" = { fg = "light-blue" }
"keyword" = { fg = "white", modifiers = [ "bold" ] }
"keyword.control" = { fg = "light-blue" }
"keyword.storage.type" = { fg = "light-blue" }
"keyword.function" = { fg = "light-blue" }
"keyword.directive" = { fg = "yellow" }

"diagnostic.warning" = { fg = "black", bg = "light-yellow" }
"diagnostic.error" = { fg = "black", bg = "light-red" }
"diagnostic.hint" = { fg = "black", bg = "light-blue" }
